### PR TITLE
Add linkify blog post

### PR DESCRIPTION
**Pull request by macklinu**
To review:

- `bundle install && bundle exec jekyll serve`
- Click [here](http://localhost:4000/2015/04/10/modifying-androids-linkify-behavior.html) to view in your browser

### CODE REVIEW

**Comment by stkent** [comment]
It might be useful to explain really early on that the initial screen is presented in a textview.

**Comment by stkent** [comment]
Does the string your textview is displaying include an http:// prefix?

**Comment by stkent** [comment]
Presumably you remove the textview xml attribute for autolinking when setting the linkify stuff programmatically?

**Comment by stkent** [comment]
All comments in, otherwise this is a :sweet_potato: post!

**Comment by macklinu** [comment]
> It might be useful to explain really early on that the initial screen is presented in a textview.

Good call. I will include a code example to show that `CardView` layout hierarchy.

> Does the string your textview is displaying include an http:// prefix?

It does not. That would be good to explain about the `Patterns.WEB_URL` regular expression mentioned in the post and how Android will parse URLs without a URI scheme (like `http`).

> Presumably you remove the textview xml attribute for autolinking when setting the linkify stuff programmatically?

I do. Thanks for pointing that out - I will be more explicit in setting that scenario up.

Thank you, @stkent!

**Comment by stkent** [comment]
:+1: :dart:

**Pull request merged**
