### PR TITLE
feat(blog): add sharable TSLint config post

### LINKED ISSUE #2: [Blog Post] Open sourcing @detroit-labs/tslint-config
https://github.com/detroit-labs/tslint-config

### PR DESCRIPTION
**Pull request by macklinu**
Resolves #2 

I feel like something's missing from this post, but putting it up for now.

### CODE REVIEW

**Comment by macklinu** [comment]
@tyndallm & @stkent - would love your feedback on this blog post. Anything feel like it's missing from the post? Anything I could be answering or that is unclear? Good as is? Thanks! 💟

**Comment by stkent** [comment]
Dude, I think this is perfect. Short, sweet, to the point, with links out for actual examples. 💯

**Comment by tyndallm** [comment]
I think it looks great man! I really dig shorter posts like this that present a solution and link to further reading. 👍

**Comment by macklinu** [comment]
Thanks for taking a look guys! :shipit:

**Pull request merged**
